import * as T from './three.module.js';
export const GUN_DRAW_RATE=1.3;
export function castTiming(kind){return {duration:['beam','rocket','revive'].includes(kind)?1.05:.78,release:['dash','updraft','satchel'].includes(kind)?.22:.42};}
export function castPose(kind,seconds){const {duration,release}=castTiming(kind),t=Math.max(0,Math.min(1,seconds/duration)),rise=Math.sin(Math.PI*t),throwing=['smoke','slow','molly','grenade','flash','satchel'].includes(kind),bow=['shock','reveal','beam'].includes(kind);return{t,release:seconds>=release,left:[-.26-rise*.07,-.62+rise*.31,-.6-rise*.15],right:[.25-rise*.05,-.63+rise*.34,-.55-(throwing&&seconds>=release?.30*rise:0)],rotation:throwing?-rise*1.8:bow?-rise*.5:-rise*.9,orb:seconds<release||['heal','revive','wall','rebirth'].includes(kind),bow};}
// Reconstructed procedural hand rig, not captured original animation.
export class AgentHands{
 constructor(scene){this.group=new T.Group();scene.add(this.group);this.group.visible=false;this.skin=new T.MeshStandardMaterial({color:0xe1b89a,roughness:.7});this.sleeve=new T.MeshStandardMaterial({color:0x496e89,roughness:.8});this.fx=new T.MeshStandardMaterial({color:0x99ffff,emissive:0x66aacc,emissiveIntensity:1.3});this.hands=[];this.fingers=[];const sphere=new T.SphereGeometry(1,10,8);for(const side of[-1,1]){const g=new T.Group();this.group.add(g);this.hands.push(g);const add=(x,y,z,w,h,d,m)=>{const mesh=new T.Mesh(sphere,m);mesh.position.set(x,y,z);mesh.scale.set(w,h,d);g.add(mesh);return mesh;};add(0,-.16,.03,.066,.22,.067,this.sleeve);add(0,.035,0,.064,.10,.034,this.skin);for(let i=0;i<4;i++){const f=add((i-1.5)*.031,.13,-.015,.014,.065,.016,this.skin);this.fingers.push(f);}const thumb=add(-side*.068,.055,0,.023,.063,.023,this.skin);thumb.rotation.z=side*.5;}this.orb=new T.Mesh(new T.IcosahedronGeometry(.085,2),this.fx);this.group.add(this.orb);this.bow=new T.Mesh(new T.TorusGeometry(.24,.017,6,24,Math.PI),this.fx);this.bow.rotation.z=Math.PI/2;this.group.add(this.bow);this.arrow=new T.Mesh(new T.CylinderGeometry(.009,.009,.6,6),this.fx);this.arrow.rotation.x=Math.PI/2;this.group.add(this.arrow);this.props=new T.Group();this.group.add(this.props);this.rocket=new T.Mesh(new T.CylinderGeometry(.085,.085,.65,12),this.sleeve);this.rocket.rotation.x=Math.PI/2;this.rocket.position.set(.24,-.31,-.65);this.props.add(this.rocket);this.knives=[];for(let i=0;i<5;i++){const blade=new T.Mesh(new T.ConeGeometry(.025,.22,4),this.fx);blade.position.set((i-2)*.12,-.28+Math.abs(i-2)*.04,-.72);blade.rotation.x=-Math.PI/2;this.props.add(blade);this.knives.push(blade);}this.device=new T.Mesh(new T.BoxGeometry(.18,.12,.15),this.sleeve);this.device.position.set(.22,-.25,-.6);this.props.add(this.device);}
 update(agent,kind,seconds){const p=castPose(kind,seconds);this.rocket.visible=kind==='rocket';this.device.visible=['bot','drone','satchel'].includes(kind);for(const k of this.knives)k.visible=kind==='knives';this.group.visible=true;this.skin.color.setHex(agent.colors[3]);this.sleeve.color.setHex(agent.colors[0]);this.fx.color.setHex(agent.colors[2]);this.fx.emissive.setHex(agent.colors[2]);for(let i=0;i<2;i++){this.hands[i].position.fromArray(i?p.right:p.left);this.hands[i].rotation.set(p.rotation,i?-.2:.3,i?-.25:.25);}for(const f of this.fingers)f.rotation.x=Math.sin(p.t*Math.PI)*.8;this.orb.visible=p.orb&&!p.bow&&!['rocket','knives','bot','drone','satchel'].includes(kind);this.orb.position.set(0,-.28,-.65);this.orb.rotation.y=seconds*5;this.orb.scale.setScalar(1+Math.sin(seconds*9)*.12);this.bow.visible=this.arrow.visible=p.bow;this.bow.position.set(-.22,-.23,-.72);this.arrow.position.set(-.10,-.25,-.6-Math.max(0,seconds-.42)*2);}
 hide(){this.group.visible=false;}
}
