import {WEAPONS} from './rules.js';
import {ARMOR_SHOP,shopAction,armorOwned} from './match-economy.js';
const shield=(heavy=false)=>`<svg viewBox="0 0 64 72" aria-hidden="true"><path d="M32 5 56 15 51 44 32 65 13 44 8 15Z" fill="none" stroke="currentColor" stroke-width="4"/><path d="${heavy?'M21 21h22v20L32 51 21 41Z':'m32 20 4 9 10 1-8 7 2 10-8-5-8 5 2-10-8-7 10-1Z'}" fill="currentColor"/></svg>`;
export function shopMarkup({team=false,phase,money,primary,sidearm='classic',armor,armorType,armorPool=0,ledger,agent,kit,teammates=[],round=1}){
 const state={money,primary,sidearm,armor,armorType,armorPool};
 const gun=id=>{const w=WEAPONS[id],owned=w.slot==='sidearm'?id===sidearm:id===primary,r=WEAPONS[id].slot==='sidearm'?ledger?.sidearm:ledger?.weapon,refund=r?.id===id,decision=shopAction(state,ledger,id,{phase,team});return `<div class="shop-item ${owned?'owned':''} ${!decision.ok&&!owned?'unaffordable':''}"><button class="shop-purchase" data-buy="${id}" ${decision.ok?'':'disabled'} aria-label="${w.name}，${owned?'已拥有':decision.ok?'购买 '+(team?0:w.cost):decision.reason}"><span class="shop-name">${w.name}</span><img src="assets/ui/${id}.png" alt=""><strong>${owned?'已拥有':`¤ ${team?0:w.cost}`}</strong>${!owned&&!decision.ok?'<small>余额不足</small>':''}</button>${refund?`<button class="shop-refund" data-refund="${id}">退款 +${r.cost}</button>`:''}</div>`;};
 const section=(title,ids)=>`<section class="shop-category"><h3>${title}</h3><div class="shop-category-items">${ids.map(gun).join('')}</div></section>`;
 const armorCards=Object.entries(ARMOR_SHOP).map(([id,w])=>{const owned=armorOwned(state,id),refund=ledger?.armor?.id===id,decision=shopAction(state,ledger,id,{phase,team});return `<div class="shop-item armor-item ${owned?'owned':''} ${!decision.ok&&!owned?'unaffordable':''}"><button class="shop-purchase" data-buy="${id}" ${decision.ok?'':'disabled'} aria-label="${w.name}，${owned?'已拥有':decision.ok?'购买 '+(team?0:w.cost):decision.reason}"><span class="shop-name">${w.name}</span>${id==='regen'?'<span class="regen-symbol">⟳</span>':shield(w.armor===50)}<strong>${owned?'已拥有':`¤ ${team?0:w.cost}`}</strong><small>${owned?Math.ceil(armor)+' / '+w.armor:'护甲 '+w.armor+(w.pool?' · 储备 '+w.pool:'')}</small></button>${refund?`<button class="shop-refund" data-refund="${id}">退款 +${ledger.armor.cost}</button>`:''}</div>`;}).join('');
 const skills=[3,0,1,2].map(i=>{const sk=agent.skills[i],n=i===3?kit?.points||0:kit?.charges[i]??sk.charges,max=i===3?agent.ultimateCost:sk.charges;return `<div class="shop-skill" title="${sk.description}"><span class="shop-name">${sk.name}</span><img src="${sk.icon}" alt=""><strong>${i===3?n+' / '+max+' 充能':n===max?'已满':n+' / '+max}</strong></div>`;}).join('');
 return `<div class="dialog-head shop-head"><h2>${team?'团队军备':'购买阶段'}<small>${team?'免费装备':'第 '+round+' 回合'}</small></h2><button class="close" id="closeOverlay" aria-label="关闭购买界面">×</button></div><div class="shop-scroll"><div class="shop-layout"><aside class="shop-roster"><div class="shop-player"><img src="${agent.icon}" alt="${agent.name}"><strong>¤ ${money.toLocaleString()}</strong><span>${agent.name}</span><div><span class="shop-shield">${shield()}<b>${Math.ceil(armor)}</b></span><img src="assets/ui/${primary==='classic'?sidearm:primary}.png" alt="${WEAPONS[primary==='classic'?sidearm:primary].name}"></div></div>${teammates.map(t=>`<div class="shop-teammate ${t.alive?'':'down'}"><img src="${t.icon}" alt=""><span>${t.name}<small>${t.alive?'队友':'阵亡'}</small></span></div>`).join('')}</aside><div class="shop-column">${section('佩枪',['classic','shorty','frenzy','ghost','bandit','sheriff'])}</div><div class="shop-column">${section('冲锋枪',['stinger','spectre'])}${section('霰弹枪',['bucky','judge'])}</div><div class="shop-column">${section('步枪',['bulldog','guardian','phantom','vandal'])}</div><div class="shop-column">${section('狙击枪',['marshal','outlaw','operator'])}${section('机枪',['ares','odin'])}</div><section class="shop-category shop-armor"><h3>护甲</h3><div class="shop-category-items">${armorCards}</div></section><section class="shop-category shop-skills"><h3>技能</h3><div class="shop-category-items">${skills}</div></section></div></div><div class="shop-footer"><p>${team?'团队模式可免费更换装备':'新购装备可点「退款」退还 · 换购自动抵扣原价'}</p><div><button class="secondary" id="skipBuy">${phase==='buy'?'准备完毕':'返回战场'}</button><button class="primary" id="buyDone">完成购买</button></div></div>`;
}
